### ISSUE TITLE
Clarify use of package in README

### ISSUE THREAD

**Issue by BurtHarris** [jhaker/nodejs-dotnet#1]
The package name (dotnet) lead me to hope this was a node.js <-> common language runtime interop package.   Reading https://www.npmjs.com/package/dotnet left me unsure.   It took digging into the sources to see that this is a command-line wrapper, not a runtime package.    It would be nice if the README made that clearer.

Thanks

**Comment by BurtHarris** [comment]
P.S.   I found the sort of thing I was looking for at https://www.npmjs.com/package/clr

**Comment by jhaker** [comment]
You might also try edge. https://github.com/tjanczuk/edge

I'm considering changing the original scope or plan for this project and welcome any feedback, ideas or contributions. If edge and clr don't exactly fit your need please explain.  Be happy to help.

**Comment by jhaker** [comment]
Thanks for the suggestion. Updated the readme.
